# Generated by Django 5.1.7 on 2025-03-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_staff_is_available_stafftask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='event_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='auth_app.eventmanager'),
        ),
    ]
